spring.application.name=esibuy-backend
app.cors.allowed-origin=http://localhost:43127
spring.jackson.deserialization.fail-on-unknown-properties=true
esibuy.seguridad.pepper=${ESIBUY_PEPPER:}
esibuy.limite-registro.max-peticiones=5
esibuy.limite-registro.ventana=PT1M
spring.jackson.default-leniency=false
