package com.esibuy.esibuy_backend.excepcion;

public enum CodigoError {
    OBLIGATORIO,
    FORMATO_INVALIDO,
    LONGITUD_EXCESIVA,
    MENOR_DE_EDAD,
    FECHA_INVALIDA,
    DOMINIO_EMAIL_INEXISTENTE,
    TELEFONO_INVALIDO,
    AVATAR_NO_PERMITIDO,
    CATEGORIA_INEXISTENTE,
    NOMBRE_COMERCIAL_DUPLICADO,
    CONTRASENAS_NO_COINCIDEN,
    CONTRASENA_CORTA,
    CONTRASENA_LARGA,
    CONTRASENA_COMUN,
    CONTRASENA_FILTRADA,
    CONTRASENA_CON_DATOS_PERSONALES
}
